app = "french-test-app"
primary_region = "cdg"

[build]

[deploy]
  release_command = "sh -c 'python manage.py migrate --noinput && python manage.py load_questions && python manage.py loaddata french_test_app/fixtures/resources.json'"

[env]
  DJANGO_SETTINGS_MODULE = "config.settings.production"
  DJANGO_ALLOWED_HOSTS = ".fly.dev"
  DJANGO_SECURE_SSL_REDIRECT = "False"
  WEB_CONCURRENCY = "2"
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1
