# Generated by Django 6.0.4 on 2026-05-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('capsule_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('topic', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('orthographe', 'Orthographe'), ('syntaxe', 'Syntaxe'), ('vocabulaire', 'Vocabulaire')], default='orthographe', max_length=20)),
                ('material_type', models.CharField(choices=[('capsule', 'Capsule'), ('theorie', 'Théorie'), ('exercice', 'Exercice'), ('corrige', 'Corrigé'), ('mise_en_situation', 'Mise en situation'), ('autre', 'Autre')], default='autre', max_length=20)),
                ('pdf_file', models.FileField(upload_to='resources/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['category', 'order', 'capsule_number', 'material_type'],
            },
        ),
    ]
