# Generated by Django 6.0.4 on 2026-05-03 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='capsule_topic',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='source',
            field=models.CharField(choices=[('exam', 'Examen'), ('capsule', 'Capsule'), ('serie', 'Série')], default='exam', max_length=10),
        ),
    ]
